version: '3.8'

services:
  posrgres-database:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval  : 1s
      timeout: 5s
      retries: 10