version: '3.8'

services:
  postgres-database:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DEFAULT_DATABASE}
      - POSTGRES_USER=${DEFAULT_USER}
      - POSTGRES_PASSWORD=${DEFAULT_USER_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval  : 1s
      timeout: 5s
      retries: 10